### ISSUE TITLE
Can't access WU

### ISSUE THREAD

**Issue by jameswright** [kylefortin/WarlockUtilities#5]
I've installed the plugin and can see it registered. When WoW Classic starts WU say's hello in the chat window.

If I then type /wu I get the help text.

But if I type /wy config I can't press return.

What am I doing wrong?

**Comment by kylefortin** [comment]
Just confirming that `/wy config` is a typo in your post, command should be `/wu config`.

**Comment by jameswright** [comment]
Sorry, yes, it's /wu config I've also tried /warlockutilities and /warlockutils

All show the help text, but as soon as I try /wu config I can't press return. Weird.

**Comment by kylefortin** [comment]
Thanks for confirming. Unfortunately I am unable to replicate the issue on the latest release with an up to date client. May be an interaction with another addon, would recommend disabling other addons and seeing if you are able to execute the config command again.

Could also see if you can get to the options window via the game menu (options, addons, WarlockUtilities).

**Comment by jameswright** [comment]
I've disabled all but WU, same problem, are their any dependencies I need to install?

**Comment by kylefortin** [comment]
Hmm. The addon is built on the Ace3 framework, but that is all packaged in the install, shouldn't be anything else needed. If you try to go in through the game menu (menu, options, addons, WU), are the config options available? Trying to see if the issue lies in registering the options panel or registering the command lines to open it. The fact that the help dialog appears as normal makes me think it is related to the former.

**Comment by jameswright** [comment]
I've just uploaded this video to youtube if it helps:-

https://www.youtube.com/watch?v=-DKu55QUqHc

**Comment by kylefortin** [comment]
Ah yes that does help, you are on Classic Era on an old version of the addon. This is currently only being supported for Classic (WotLK). I can look into forking a copy of the v1.x version to work with Classic Era.

**Comment by jameswright** [comment]
Sorry, I perhaps should've been clearer. If it helps I installed it via CurseForge which seemed to intimate it would work on Classic Era.

![image](https://github.com/kylefortin/WarlockUtilities/assets/79183/396685f7-ddc1-4b3b-a7bb-f36327f9964e)

**Comment by kylefortin** [comment]
No worries. I'm actually surprised that the CurseForge client treats 1.13.x compatible addons as valid for 1.14.x clients. There were a myriad of client side API changes that occurred over the changes to 2.x and 3.x client versions. The major issue here was an update to the Ace3 library files that occurred at the update to 2.x (Burning Crusade). I have uploaded a new version (`3.4.1`) to CurseForge that will add compatibility for the Classic Era client. Please note that the Demon Manager UI will still show an option for summoning the Felguard, although it will always be flagged as disabled. Due to the way the localization file is structured, it is not a simple fix to remove the option. The new version has been flagged as valid for 3.4.2 and 1.14.4 clients, so the CurseForge client should prompt you to update for both WotLK and Classic.
